theme: jekyll-theme-hacker
source: .
title: "Suchben's blog"
email: 283226372@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  学习日志.
baseurl: "/books" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  suchben
collections:
  posts:
    output: true
  topics
collections_dir: _collections
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
